-- =====================================================================
-- Toán Mô Hình Hà Nội Portal — Supabase Schema
-- =====================================================================
-- Apply via Supabase SQL editor. Assumes a clean `public` schema
-- (pre-launch: no data preservation).
-- =====================================================================

-- ---------- Enums ---------------------------------------------------------

do $$ begin
    create type public.user_role as enum ('user', 'admin');
exception when duplicate_object then null; end $$;

do $$ begin
    create type public.post_category as enum ('news', 'announcement', 'tutorial', 'result');
exception when duplicate_object then null; end $$;

do $$ begin
    create type public.contest_participation_type as enum ('individual', 'team', 'both');
exception when duplicate_object then null; end $$;

do $$ begin
    create type public.contest_status as enum ('draft', 'open', 'ongoing', 'closed', 'cancelled');
exception when duplicate_object then null; end $$;

do $$ begin
    create type public.registration_status as enum ('pending', 'approved', 'rejected', 'withdrawn');
exception when duplicate_object then null; end $$;

do $$ begin
    create type public.member_role as enum ('leader', 'member');
exception when duplicate_object then null; end $$;

-- ---------- Drop tables (reverse dependency order) ------------------------

drop table if exists public.submission            cascade;
drop table if exists public.registration_member   cascade;
drop table if exists public.contest_registration  cascade;
drop table if exists public.post_tags             cascade;
drop table if exists public.contest               cascade;
drop table if exists public.post                  cascade;
drop table if exists public.tag                   cascade;
drop table if exists public.users                 cascade;

-- ---------- Tables --------------------------------------------------------

create table public.users (
    id            uuid              primary key,
    username      text              not null unique,
    display_name  text,
    bio           text,
    school        text,
    role          public.user_role  not null default 'user',
    created_at    timestamptz       not null default now(),
    updated_at    timestamptz
);

create table public.post (
    id            bigint                generated by default as identity primary key,
    slug          text                  not null unique,
    title         text                  not null,
    description   text                  not null,
    content       text                  not null,
    image_url     text,
    category      public.post_category  not null default 'news',
    published     boolean               not null default false,
    published_at  timestamptz,
    created_at    timestamptz           not null default now(),
    updated_at    timestamptz
);

create table public.tag (
    id         bigint      generated by default as identity primary key,
    name       text        not null unique,
    slug       text        not null unique,
    created_at timestamptz not null default now()
);

create table public.post_tags (
    post_id    bigint      not null,
    tag_id     bigint      not null,
    created_at timestamptz not null default now(),
    primary key (post_id, tag_id)
);

create table public.contest (
    id                  bigint                             generated by default as identity primary key,
    slug                text                               not null unique,
    title               text                               not null,
    description         text                               not null,
    rules               text,
    cover_image_url     text,
    participation_type  public.contest_participation_type  not null default 'individual',
    max_team_size       smallint                           not null default 1,
    registration_start  timestamptz                        not null,
    registration_end    timestamptz                        not null,
    contest_start       timestamptz                        not null,
    contest_end         timestamptz                        not null,
    submission_deadline timestamptz                        not null,
    status              public.contest_status              not null default 'draft',
    created_at          timestamptz                        not null default now(),
    updated_at          timestamptz
);

create table public.contest_registration (
    id            bigint                      generated by default as identity primary key,
    contest_id    bigint                      not null,
    team_name     text,
    status        public.registration_status  not null default 'pending',
    registered_at timestamptz                 not null default now(),
    updated_at    timestamptz
);

create table public.registration_member (
    registration_id bigint             not null,
    user_id         uuid               not null,
    role            public.member_role not null default 'member',
    joined_at       timestamptz        not null default now(),
    primary key (registration_id, user_id)
);

-- Uniqueness of (user, contest) enforced at application layer (subquery index
-- not supported in Postgres); see contests-db.ts in Phase 2.

create table public.submission (
    id              bigint      generated by default as identity primary key,
    registration_id bigint      not null,
    storage_path    text        not null,
    file_name       text        not null,
    file_size_bytes bigint      not null,
    mime_type       text        not null,
    note            text,
    submitted_by    uuid        not null,
    submitted_at    timestamptz not null default now(),
    is_final        boolean     not null default false
);

-- ---------- Constraints: foreign keys -------------------------------------

alter table public.users
    add constraint users_auth_fk
        foreign key (id) references auth.users(id)
        on delete cascade;  -- on update: no action (auth UUID không bao giờ thay đổi)

alter table public.post_tags
    add constraint post_tags_post_fk
        foreign key (post_id) references public.post(id)
        on delete cascade,  -- on update: no action (identity PK không thay đổi)
    add constraint post_tags_tag_fk
        foreign key (tag_id) references public.tag(id)
        on delete cascade;  -- on update: no action (identity PK không thay đổi)

alter table public.contest_registration
    add constraint contest_registration_contest_fk
        foreign key (contest_id) references public.contest(id)
        on delete cascade;  -- on update: no action (identity PK không thay đổi)

alter table public.registration_member
    add constraint registration_member_registration_fk
        foreign key (registration_id) references public.contest_registration(id)
        on delete cascade,  -- on update: no action (identity PK không thay đổi)
    add constraint registration_member_user_fk
        foreign key (user_id) references public.users(id)
        on delete cascade;  -- on update: no action (auth UUID không bao giờ thay đổi)

alter table public.submission
    add constraint submission_registration_fk
        foreign key (registration_id) references public.contest_registration(id)
        on delete cascade,  -- on update: no action (identity PK không thay đổi)
    add constraint submission_submitted_by_fk
        foreign key (submitted_by) references public.users(id);
        -- on delete: no action (giữ lịch sử nộp bài khi user bị xoá); on update: no action (auth UUID không bao giờ thay đổi)

-- ---------- Constraints: check --------------------------------------------

alter table public.users
    add constraint users_username_len check (char_length(username) between 3 and 30),
    add constraint users_username_fmt check (username ~ '^[a-z0-9_]+$');

alter table public.post
    add constraint post_publish_check check (
        (published = false and published_at is null) or
        (published = true  and published_at is not null)
    );

alter table public.tag
    add constraint tag_name_len check (char_length(name) <= 30);

alter table public.contest
    add constraint contest_team_size_check check (
        (participation_type = 'individual' and max_team_size = 1) or
        (participation_type in ('team', 'both') and max_team_size >= 2)
    ),
    add constraint contest_date_order_check check (
        registration_start < registration_end and
        registration_end   <= contest_start   and
        contest_start      < contest_end      and
        contest_end        <= submission_deadline
    );

alter table public.submission
    add constraint submission_file_size_check check (file_size_bytes > 0);

-- ---------- Indexes -------------------------------------------------------

create index if not exists idx_post_published_at    on public.post (published, published_at desc);
create index if not exists idx_post_category        on public.post (category);
create index if not exists idx_post_tags_tag_id     on public.post_tags (tag_id);
create index if not exists idx_contest_status       on public.contest (status);
create index if not exists idx_contest_reg_end      on public.contest (registration_end);
create index if not exists idx_registration_ctx     on public.contest_registration (contest_id, status);
create index if not exists idx_member_user_id       on public.registration_member (user_id);
create index if not exists idx_submission_reg_final on public.submission (registration_id, is_final);

-- At most one is_final=true submission per registration.
drop index if exists uq_submission_final_per_registration;
create unique index uq_submission_final_per_registration
    on public.submission (registration_id)
    where is_final = true;

-- ---------- Functions & Triggers ------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at
    before update on public.users
    for each row execute function public.set_updated_at();

drop trigger if exists trg_post_updated_at on public.post;
create trigger trg_post_updated_at
    before update on public.post
    for each row execute function public.set_updated_at();

drop trigger if exists trg_contest_updated_at on public.contest;
create trigger trg_contest_updated_at
    before update on public.contest
    for each row execute function public.set_updated_at();

drop trigger if exists trg_registration_updated_at on public.contest_registration;
create trigger trg_registration_updated_at
    before update on public.contest_registration
    for each row execute function public.set_updated_at();

-- Create public.users row from a new auth.users row.
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    base_username  text;
    final_username text;
    counter        int := 0;
begin
    base_username := lower(regexp_replace(split_part(new.email, '@', 1), '[^a-z0-9_]', '_', 'g'));

    if char_length(base_username) < 3 then
        base_username := base_username || '_usr';
    end if;

    final_username := base_username;

    while exists (select 1 from public.users where username = final_username) loop
        counter := counter + 1;
        final_username := base_username || counter::text;
    end loop;

    insert into public.users (id, username, display_name)
    values (
        new.id,
        final_username,
        coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name')
    );

    return new;
end;
$$;

drop trigger if exists trg_on_auth_user_created on auth.users;
create trigger trg_on_auth_user_created
    after insert on auth.users
    for each row
    execute function public.handle_new_auth_user();

-- Role helper (SECURITY DEFINER so RLS on `users` does not short-circuit it).
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1 from public.users
        where id = auth.uid() and role = 'admin'
    );
$$;

-- ---------- Row Level Security --------------------------------------------

alter table public.users                 enable row level security;
alter table public.post                  enable row level security;
alter table public.tag                   enable row level security;
alter table public.post_tags             enable row level security;
alter table public.contest               enable row level security;
alter table public.contest_registration  enable row level security;
alter table public.registration_member   enable row level security;
alter table public.submission            enable row level security;

-- users
drop policy if exists "users: public read"   on public.users;
create policy "users: public read"
    on public.users for select
    using (true);

drop policy if exists "users: owner update"  on public.users;
create policy "users: owner update"
    on public.users for update
    using  (auth.uid() = id)
    with check (auth.uid() = id);

-- post
drop policy if exists "post: public read published" on public.post;
create policy "post: public read published"
    on public.post for select
    using (published = true);

-- tag (public read)
drop policy if exists "tag: public read" on public.tag;
create policy "tag: public read"
    on public.tag for select
    using (true);

-- post_tags (public read; client-side filter by published post)
drop policy if exists "post_tags: public read" on public.post_tags;
create policy "post_tags: public read"
    on public.post_tags for select
    using (true);

-- contest
drop policy if exists "contest: public read non-draft" on public.contest;
create policy "contest: public read non-draft"
    on public.contest for select
    using (status <> 'draft' or public.is_admin());

-- contest_registration
drop policy if exists "registration: member or admin read" on public.contest_registration;
create policy "registration: member or admin read"
    on public.contest_registration for select
    using (
        public.is_admin() or
        id in (
            select registration_id from public.registration_member
            where user_id = auth.uid()
        )
    );

-- registration_member
drop policy if exists "registration_member: member or admin read" on public.registration_member;
create policy "registration_member: member or admin read"
    on public.registration_member for select
    using (
        public.is_admin() or
        user_id = auth.uid() or
        registration_id in (
            select registration_id from public.registration_member
            where user_id = auth.uid()
        )
    );

-- submission
drop policy if exists "submission: member or admin read" on public.submission;
create policy "submission: member or admin read"
    on public.submission for select
    using (
        public.is_admin() or
        registration_id in (
            select registration_id from public.registration_member
            where user_id = auth.uid()
        )
    );

drop policy if exists "submission: approved member insert" on public.submission;
create policy "submission: approved member insert"
    on public.submission for insert
    with check (
        submitted_by = auth.uid() and
        exists (
            select 1
            from public.registration_member m
            join public.contest_registration r on r.id = m.registration_id
            where m.user_id = auth.uid()
              and m.registration_id = submission.registration_id
              and r.status = 'approved'
        )
    );

-- ---------- Storage buckets -----------------------------------------------

insert into storage.buckets (id, name, public)
values ('post-images', 'post-images', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('submissions', 'submissions', false)
on conflict (id) do nothing;

-- post-images: public read; writes via service role only.
drop policy if exists "post-images: public read" on storage.objects;
create policy "post-images: public read"
    on storage.objects for select
    using (bucket_id = 'post-images');

-- submissions: member-or-admin read; member insert.
drop policy if exists "submissions: member or admin read" on storage.objects;
create policy "submissions: member or admin read"
    on storage.objects for select
    using (
        bucket_id = 'submissions' and (
            public.is_admin() or
            (storage.foldername(name))[2]::bigint in (
                select registration_id from public.registration_member
                where user_id = auth.uid()
            )
        )
    );

drop policy if exists "submissions: member insert" on storage.objects;
create policy "submissions: member insert"
    on storage.objects for insert
    with check (
        bucket_id = 'submissions' and
        (storage.foldername(name))[2]::bigint in (
            select registration_id from public.registration_member
            where user_id = auth.uid()
        )
    );

-- ---------- Realtime recommendations --------------------------------------
-- Bật Realtime qua Dashboard hoặc:
--   alter publication supabase_realtime add table public.<tên_bảng>;
--
-- NÊN bật:
--   contest               — client tự cập nhật status (open/ongoing/closed) mà
--                           không cần reload; dùng cho trang danh sách kỳ thi.
--   contest_registration  — admin thấy đăng ký mới ngay lập tức; team thấy
--                           trạng thái duyệt (pending→approved/rejected) đổi live.
--   submission            — team thấy xác nhận nộp bài, admin theo dõi bài nộp
--                           cuối (is_final) mà không cần polling.
--
-- KHÔNG cần bật:
--   users                 — dữ liệu profile, thay đổi thấp, không cần push live.
--   post / tag / post_tags — nội dung tĩnh, đủ dùng ISR/revalidateTag.
--   registration_member   — thay đổi ít, đọc theo registration đã load sẵn.
