-- =====================================================================
-- Migration 0000: NUCLEAR RESET + FULL INIT (v0.2.0 schema)
-- =====================================================================
-- WARNING — DESTRUCTIVE.
-- This script wipes the entire `public` schema for this project (all
-- tables, types, functions, triggers, storage policies) and recreates
-- everything from scratch using the v0.2.0 canonical schema:
--   * Two-layer contest timeline (contest.start_at/end_at + contest_stage)
--   * Simplified contest_status enum (draft|active|closed|cancelled)
--
-- Use this when you want to start cold from a fresh database. After
-- running this, you do NOT need to run 0001_* or 0002_* — they are
-- already incorporated.
--
-- DO NOT run this on a production database with real data.
-- =====================================================================

-- ---------- 0. Drop storage policies ---------------------------------------

drop policy if exists "post-images: public read"          on storage.objects;
drop policy if exists "submissions: member or admin read" on storage.objects;
drop policy if exists "submissions: member insert"        on storage.objects;

-- ---------- 1. Drop triggers on auth.users ---------------------------------

drop trigger if exists trg_on_auth_user_created on auth.users;

-- ---------- 2. Drop policies on public tables ------------------------------
--   Must drop before tables/columns/types they depend on. Wrapped in DO so
--   missing tables don't abort the script.

do $$
declare
    rec record;
begin
    for rec in
        select schemaname, tablename, policyname
        from pg_policies
        where schemaname = 'public'
    loop
        execute format(
            'drop policy if exists %I on %I.%I',
            rec.policyname, rec.schemaname, rec.tablename
        );
    end loop;
end $$;

-- ---------- 3. Drop tables (reverse dependency order) ----------------------

drop table if exists public.submission            cascade;
drop table if exists public.registration_member   cascade;
drop table if exists public.contest_registration  cascade;
drop table if exists public.contest_stage         cascade;
drop table if exists public.post_tags             cascade;
drop table if exists public.contest               cascade;
drop table if exists public.post                  cascade;
drop table if exists public.tag                   cascade;
drop table if exists public.users                 cascade;

-- ---------- 4. Drop functions ----------------------------------------------

drop function if exists public.handle_new_auth_user() cascade;
drop function if exists public.is_admin()             cascade;
drop function if exists public.set_updated_at()       cascade;

-- ---------- 5. Drop custom enum types --------------------------------------

drop type if exists public.user_role                  cascade;
drop type if exists public.post_category              cascade;
drop type if exists public.contest_participation_type cascade;
drop type if exists public.contest_status             cascade;
drop type if exists public.registration_status        cascade;
drop type if exists public.member_role                cascade;

-- =====================================================================
-- FULL INIT — mirrors supabase/schema.sql (v0.2.0 canonical DDL)
-- =====================================================================

-- ---------- Enums ---------------------------------------------------------

create type public.user_role                  as enum ('user', 'admin');
create type public.post_category              as enum ('news', 'announcement', 'tutorial', 'result');
create type public.contest_participation_type as enum ('individual', 'team', 'both');
create type public.contest_status             as enum ('draft', 'active', 'closed', 'cancelled');
create type public.registration_status        as enum ('pending', 'approved', 'rejected', 'withdrawn');
create type public.member_role                as enum ('leader', 'member');

-- ---------- Tables --------------------------------------------------------

create table public.users (
    id            uuid              primary key,
    username      text              not null unique,
    display_name  text,
    bio           text,
    school        text,
    role          public.user_role  not null default 'user',
    created_at    timestamptz       not null default now(),
    updated_at    timestamptz,
    constraint chk_display_name_len check (display_name is null or char_length(display_name) <= 100),
    constraint chk_bio_len          check (bio is null or char_length(bio) <= 500),
    constraint chk_school_len       check (school is null or char_length(school) <= 200)
);

create table public.post (
    id            bigint                generated by default as identity primary key,
    slug          text                  not null unique,
    title         text                  not null,
    description   text                  not null,
    content       text                  not null,
    image_url     text,
    category      public.post_category  not null default 'news',
    published     boolean               not null default false,
    published_at  timestamptz,
    created_at    timestamptz           not null default now(),
    updated_at    timestamptz
);

create table public.tag (
    id         bigint      generated by default as identity primary key,
    name       text        not null unique,
    slug       text        not null unique,
    created_at timestamptz not null default now()
);

create table public.post_tags (
    post_id    bigint      not null,
    tag_id     bigint      not null,
    created_at timestamptz not null default now(),
    primary key (post_id, tag_id)
);

create table public.contest (
    id                  bigint                             generated by default as identity primary key,
    slug                text                               not null unique,
    title               text                               not null,
    description         text                               not null,
    rules               text,
    cover_image_url     text,
    participation_type  public.contest_participation_type  not null default 'individual',
    max_team_size       smallint                           not null default 1,
    start_at            timestamptz                        not null,
    end_at              timestamptz                        not null,
    status              public.contest_status              not null default 'draft',
    created_at          timestamptz                        not null default now(),
    updated_at          timestamptz
);

-- contest_stage: dynamic n-stage timeline. Stages may overlap. Each stage
-- independently enables registration / submission. Stage windows must fit
-- inside [contest.start_at, contest.end_at] (validated at the application
-- layer in src/lib/contests-db.ts).
create table public.contest_stage (
    id                 bigint        generated by default as identity primary key,
    contest_id         bigint        not null,
    name               text          not null,
    description        text,
    start_at           timestamptz   not null,
    end_at             timestamptz   not null,
    allow_registration boolean       not null default false,
    allow_submission   boolean       not null default false,
    allow_resubmit     boolean       not null default false,
    submission_type    text,
    display_order      integer       not null default 0,
    created_at         timestamptz   not null default now(),
    updated_at         timestamptz
);

create table public.contest_registration (
    id            bigint                      generated by default as identity primary key,
    contest_id    bigint                      not null,
    team_name     text,
    status        public.registration_status  not null default 'pending',
    registered_at timestamptz                 not null default now(),
    updated_at    timestamptz
);

create table public.registration_member (
    registration_id bigint             not null,
    user_id         uuid               not null,
    role            public.member_role not null default 'member',
    joined_at       timestamptz        not null default now(),
    primary key (registration_id, user_id)
);

create table public.submission (
    id              bigint      generated by default as identity primary key,
    registration_id bigint      not null,
    storage_path    text        not null,
    file_name       text        not null,
    file_size_bytes bigint      not null,
    mime_type       text        not null,
    note            text,
    submitted_by    uuid        not null,
    submitted_at    timestamptz not null default now(),
    is_final        boolean     not null default false
);

-- ---------- Foreign keys --------------------------------------------------

alter table public.users
    add constraint users_auth_fk
        foreign key (id) references auth.users(id)
        on delete cascade;

alter table public.post_tags
    add constraint post_tags_post_fk
        foreign key (post_id) references public.post(id) on delete cascade,
    add constraint post_tags_tag_fk
        foreign key (tag_id)  references public.tag(id)  on delete cascade;

alter table public.contest_stage
    add constraint contest_stage_contest_fk
        foreign key (contest_id) references public.contest(id) on delete cascade;

alter table public.contest_registration
    add constraint contest_registration_contest_fk
        foreign key (contest_id) references public.contest(id) on delete cascade;

alter table public.registration_member
    add constraint registration_member_registration_fk
        foreign key (registration_id) references public.contest_registration(id) on delete cascade,
    add constraint registration_member_user_fk
        foreign key (user_id) references public.users(id) on delete cascade;

alter table public.submission
    add constraint submission_registration_fk
        foreign key (registration_id) references public.contest_registration(id) on delete cascade,
    add constraint submission_submitted_by_fk
        foreign key (submitted_by) references public.users(id);

-- ---------- Check constraints ---------------------------------------------

alter table public.users
    add constraint users_username_len check (char_length(username) between 3 and 30),
    add constraint users_username_fmt check (username ~ '^[a-z0-9_]+$');

alter table public.post
    add constraint post_publish_check check (
        (published = false and published_at is null) or
        (published = true  and published_at is not null)
    );

alter table public.tag
    add constraint tag_name_len check (char_length(name) <= 30);

alter table public.contest
    add constraint contest_team_size_check check (
        (participation_type = 'individual' and max_team_size = 1) or
        (participation_type in ('team', 'both') and max_team_size >= 2)
    ),
    add constraint contest_grand_order check (start_at < end_at);

alter table public.contest_stage
    add constraint contest_stage_order_check check (start_at < end_at);

alter table public.submission
    add constraint submission_file_size_check check (file_size_bytes > 0);

-- ---------- Indexes -------------------------------------------------------

create index idx_post_published_at     on public.post (published, published_at desc);
create index idx_post_category         on public.post (category);
create index idx_post_tags_tag_id      on public.post_tags (tag_id);
create index idx_contest_status        on public.contest (status);
create index idx_contest_window        on public.contest (start_at, end_at);
create index idx_contest_stage_contest on public.contest_stage (contest_id, display_order);
create index idx_contest_stage_window  on public.contest_stage (start_at, end_at);
create index idx_registration_ctx      on public.contest_registration (contest_id, status);
create index idx_member_user_id        on public.registration_member (user_id);
create index idx_submission_reg_final  on public.submission (registration_id, is_final);

create unique index uq_submission_final_per_registration
    on public.submission (registration_id)
    where is_final = true;

-- ---------- Functions & Triggers ------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger trg_users_updated_at
    before update on public.users
    for each row execute function public.set_updated_at();

create trigger trg_post_updated_at
    before update on public.post
    for each row execute function public.set_updated_at();

create trigger trg_contest_updated_at
    before update on public.contest
    for each row execute function public.set_updated_at();

create trigger trg_contest_stage_updated_at
    before update on public.contest_stage
    for each row execute function public.set_updated_at();

create trigger trg_registration_updated_at
    before update on public.contest_registration
    for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    base_username  text;
    final_username text;
    counter        int := 0;
begin
    base_username := lower(regexp_replace(split_part(new.email, '@', 1), '[^a-z0-9_]', '_', 'g'));

    if char_length(base_username) < 3 then
        base_username := base_username || '_usr';
    end if;

    final_username := base_username;

    while exists (select 1 from public.users where username = final_username) loop
        counter := counter + 1;
        final_username := base_username || counter::text;
    end loop;

    insert into public.users (id, username, display_name)
    values (
        new.id,
        final_username,
        coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name')
    );

    return new;
end;
$$;

create trigger trg_on_auth_user_created
    after insert on auth.users
    for each row
    execute function public.handle_new_auth_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1 from public.users
        where id = auth.uid() and role = 'admin'
    );
$$;

-- ---------- Row Level Security --------------------------------------------

alter table public.users                 enable row level security;
alter table public.post                  enable row level security;
alter table public.tag                   enable row level security;
alter table public.post_tags             enable row level security;
alter table public.contest               enable row level security;
alter table public.contest_stage         enable row level security;
alter table public.contest_registration  enable row level security;
alter table public.registration_member   enable row level security;
alter table public.submission            enable row level security;

-- users
create policy "users: public read"
    on public.users for select
    using (true);

create policy "users: owner update"
    on public.users for update
    using  (auth.uid() = id)
    with check (auth.uid() = id);

-- post
create policy "post: public read published"
    on public.post for select
    using (published = true);

-- tag
create policy "tag: public read"
    on public.tag for select
    using (true);

-- post_tags
create policy "post_tags: public read"
    on public.post_tags for select
    using (true);

-- contest
create policy "contest: public read non-draft"
    on public.contest for select
    using (status <> 'draft' or public.is_admin());

-- contest_stage
create policy "contest_stage: public read non-draft"
    on public.contest_stage for select
    using (
        public.is_admin() or exists (
            select 1 from public.contest c
            where c.id = contest_stage.contest_id and c.status <> 'draft'
        )
    );

-- contest_registration
create policy "registration: member or admin read"
    on public.contest_registration for select
    using (
        public.is_admin() or
        id in (
            select registration_id from public.registration_member
            where user_id = auth.uid()
        )
    );

-- registration_member
create policy "registration_member: member or admin read"
    on public.registration_member for select
    using (
        public.is_admin() or
        user_id = auth.uid() or
        registration_id in (
            select registration_id from public.registration_member
            where user_id = auth.uid()
        )
    );

-- submission
create policy "submission: member or admin read"
    on public.submission for select
    using (
        public.is_admin() or
        registration_id in (
            select registration_id from public.registration_member
            where user_id = auth.uid()
        )
    );

create policy "submission: approved member insert"
    on public.submission for insert
    with check (
        submitted_by = auth.uid() and
        exists (
            select 1
            from public.registration_member m
            join public.contest_registration r on r.id = m.registration_id
            where m.user_id = auth.uid()
              and m.registration_id = submission.registration_id
              and r.status = 'approved'
        )
    );

-- ---------- Storage buckets -----------------------------------------------

insert into storage.buckets (id, name, public)
values ('post-images', 'post-images', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('submissions', 'submissions', false)
on conflict (id) do nothing;

create policy "post-images: public read"
    on storage.objects for select
    using (bucket_id = 'post-images');

create policy "submissions: member or admin read"
    on storage.objects for select
    using (
        bucket_id = 'submissions' and (
            public.is_admin() or
            (storage.foldername(name))[2]::bigint in (
                select registration_id from public.registration_member
                where user_id = auth.uid()
            )
        )
    );

create policy "submissions: member insert"
    on storage.objects for insert
    with check (
        bucket_id = 'submissions' and
        (storage.foldername(name))[2]::bigint in (
            select registration_id from public.registration_member
            where user_id = auth.uid()
        )
    );

-- ---------- Done ----------------------------------------------------------
-- After this script:
--   * The `public` schema matches supabase/schema.sql (v0.2.0).
--   * No need to run 0001_user_profile_length.sql or 0002_contest_stages.sql.
--   * Promote a user to admin via:
--       update public.users set role = 'admin' where id = '<auth-uid>';
