-- =====================================================================
-- Migration 0002: Contest Stages (Two-layer timeline)
-- =====================================================================
-- Replaces the rigid 5-date contest timeline with:
--   * Grand timeline (start_at / end_at) on contest
--   * n dynamic stages (contest_stage) — each can independently allow
--     registration/submission, may overlap, must sit within the grand
--     timeline.
--
-- Status enum simplified to: draft | active | closed | cancelled.
--
-- This is a CLEAN rewrite — existing contest rows are not migrated; any
-- pre-existing data is dropped via cascade. Apply only on a dev/staging
-- database that has no production data.
-- =====================================================================

-- ---------- 1. Drop dependent constraints/indexes -------------------------

alter table public.contest drop constraint if exists contest_date_order_check;
drop index if exists idx_contest_reg_end;

-- ---------- 2. Drop old date columns --------------------------------------

alter table public.contest
    drop column if exists registration_start,
    drop column if exists registration_end,
    drop column if exists contest_start,
    drop column if exists contest_end,
    drop column if exists submission_deadline;

-- ---------- 3. Add new grand-timeline columns -----------------------------

alter table public.contest
    add column if not exists start_at timestamptz,
    add column if not exists end_at   timestamptz;

-- Wipe any pre-existing rows (clean rewrite): mark them as drafts with
-- placeholder timeline so NOT NULL can be enforced. In a fresh DB this
-- is a no-op.
update public.contest
   set start_at = coalesce(start_at, now()),
       end_at   = coalesce(end_at,   now() + interval '30 days')
 where start_at is null or end_at is null;

alter table public.contest
    alter column start_at set not null,
    alter column end_at   set not null,
    add  constraint contest_grand_order check (start_at < end_at);

-- ---------- 4. Simplify contest_status enum -------------------------------
-- Postgres requires renaming + recreating to remove enum values. Any
-- RLS policies referencing `status` must be dropped first because column-
-- type changes are blocked when a policy depends on the column.

do $$
declare
    has_old boolean;
begin
    select exists (
        select 1 from pg_enum e
        join pg_type t on t.oid = e.enumtypid
        where t.typname = 'contest_status' and e.enumlabel = 'open'
    ) into has_old;

    if has_old then
        -- Drop policies that reference contest.status so we can alter the column.
        execute 'drop policy if exists "contest: public read non-draft" on public.contest';

        execute 'alter type public.contest_status rename to contest_status_old';

        execute $sql$create type public.contest_status as enum ('draft', 'active', 'closed', 'cancelled')$sql$;

        execute 'alter table public.contest alter column status drop default';

        execute $sql$
            alter table public.contest
                alter column status type public.contest_status
                using (case status::text
                    when 'open'     then 'active'
                    when 'ongoing'  then 'active'
                    when 'draft'    then 'draft'
                    when 'closed'   then 'closed'
                    when 'cancelled' then 'cancelled'
                    else 'draft'
                end)::public.contest_status
        $sql$;

        execute 'alter table public.contest alter column status set default ''draft''';
        execute 'drop type public.contest_status_old';

        -- Recreate the policy against the new enum.
        execute $sql$
            create policy "contest: public read non-draft"
                on public.contest for select
                using (status <> 'draft' or public.is_admin())
        $sql$;
    end if;
end $$;

-- ---------- 5. contest_stage table ----------------------------------------

create table if not exists public.contest_stage (
    id                  bigint       generated by default as identity primary key,
    contest_id          bigint       not null,
    name                text         not null,
    description         text,
    start_at            timestamptz  not null,
    end_at              timestamptz  not null,
    allow_registration  boolean      not null default false,
    allow_submission    boolean      not null default false,
    submission_type     text,
    display_order       integer      not null default 0,
    created_at          timestamptz  not null default now(),
    updated_at          timestamptz,
    constraint contest_stage_order_check check (start_at < end_at)
);

alter table public.contest_stage
    drop constraint if exists contest_stage_contest_fk;
alter table public.contest_stage
    add  constraint contest_stage_contest_fk
        foreign key (contest_id) references public.contest(id)
        on delete cascade;

create index if not exists idx_contest_stage_contest on public.contest_stage (contest_id, display_order);
create index if not exists idx_contest_stage_window  on public.contest_stage (start_at, end_at);

drop trigger if exists trg_contest_stage_updated_at on public.contest_stage;
create trigger trg_contest_stage_updated_at
    before update on public.contest_stage
    for each row execute function public.set_updated_at();

-- ---------- 6. RLS for contest_stage --------------------------------------

alter table public.contest_stage enable row level security;

drop policy if exists "contest_stage: public read non-draft" on public.contest_stage;
create policy "contest_stage: public read non-draft"
    on public.contest_stage for select
    using (
        public.is_admin() or exists (
            select 1 from public.contest c
            where c.id = contest_stage.contest_id and c.status <> 'draft'
        )
    );

-- ---------- 7. New index reflecting grand timeline ------------------------

create index if not exists idx_contest_window on public.contest (start_at, end_at);
